import Head from "next/head";
import { useState } from "react";
import HomeBackground from "../components/homeBackground";
import Search from "../components/search/search";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [isActive, setIsActive] = useState(false);

  return (
    <div>
      <Head>
        <title>Search Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HomeBackground isActive={isActive} setIsActive={setIsActive} />
        <div className={styles.title}>
          Challenge <span style={{ color: "#E6007A" }}>.</span>
        </div>
        <Search isActive={isActive} setIsActive={setIsActive} />
      </main>
    </div>
  );
}
