import Head from "next/head";
import Search from "../components/search/search";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container} style={{ backgroundColor: "#121316" }}>
      <Head>
        <title>Search Challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>
          Challenge <span style={{ color: "#E6007A" }}>.</span>
        </h2>
        <Search />
      </main>
    </div>
  );
}
